import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const arg=(name:string)=>process.argv.find(x=>x.startsWith(`--${name}=`))?.slice(name.length+3);
const decisionsPath=arg('decisions'),outputDir=arg('output-dir')??'ficcs/results/cases';assert(decisionsPath,'usage: --decisions=<adjudicated.jsonl> [--output-dir=<dir>]');
const bytes=readFileSync(decisionsPath);const manifest=JSON.parse(readFileSync(`${decisionsPath}.manifest.json`,'utf8'));assert.equal(manifest.status,'validated_complete_adjudicated_ficcs_coding');assert.equal(manifest.decision_sha256,createHash('sha256').update(bytes).digest('hex'));
const decisions=bytes.toString('utf8').trim().split('\n').map(JSON.parse),byClaim=new Map<string,any[]>();for(const row of decisions){const list=byClaim.get(row.claim_id)??[];list.push(row);byClaim.set(row.claim_id,list)}
const claims=readFileSync('ficcs/claim_extractions_v1.jsonl','utf8').trim().split('\n').map(JSON.parse),claimById=new Map(claims.map(x=>[x.claim_id,x]));
const frame=JSON.parse(readFileSync('ficcs/case_study_frame_v1.json','utf8'));mkdirSync(outputDir,{recursive:true});const outputs=[];
for(const item of frame.cases){const auditClaims=item.claim_ids.map((id:string)=>{const source=claimById.get(id);assert(source,`missing source claim ${id}`);const rows=byClaim.get(id);assert(rows&&rows.length===16,`incomplete adjudicated rows ${id}`);return{claim_id:id,source:source.source,claim:source.claim,constructs:rows.filter(x=>x.row_type==='construct'),edges:rows.filter(x=>x.row_type==='edge'),consequence:rows.find(x=>x.row_type==='consequence')}});
  const assertedConstructs=auditClaims.flatMap((x:any)=>x.constructs.filter((r:any)=>r.asserted_by_source));const assertedEdges=auditClaims.flatMap((x:any)=>x.edges.filter((r:any)=>r.asserted==='yes'));const unknown=assertedConstructs.filter((x:any)=>x.decision==='unknown');const unsupportedEdges=assertedEdges.filter((x:any)=>['proxy_only','untested'].includes(x.status));
  const audit={status:'adjudicated_case_audit',case_id:item.case_id,name:item.name,audit_focus:item.audit_focus,case_frame_version:frame.version,decisions_sha256:manifest.decision_sha256,claims:auditClaims,summary:{claims:auditClaims.length,asserted_constructs:assertedConstructs.length,unknown_asserted_constructs:unknown.length,asserted_edges:assertedEdges.length,unsupported_asserted_edges:unsupportedEdges.length},limits:['Purposively selected demonstration; not a frequency estimate.','Attribution decisions apply only to the recorded subject, unit, and period.']};
  const jsonPath=`${outputDir}/${item.case_id}.json`;writeFileSync(jsonPath,JSON.stringify(audit,null,2)+'\n');
  const rows=auditClaims.map((x:any)=>`| ${x.claim_id} | ${x.source.source_type} | ${x.claim.asserted_constructs.join(', ')} | ${x.constructs.filter((r:any)=>r.asserted_by_source&&r.decision==='unknown').map((r:any)=>r.construct).join(', ')||'none'} |`).join('\n');
  const md=`# ${item.name}: FICCS case audit\n\nStatus: adjudicated case audit. Decisions file SHA-256: \`${manifest.decision_sha256}\`.\n\n## Scope\n\nThis purposively selected demonstration contains ${auditClaims.length} frozen primary-corpus claims. It is not a frequency estimate or a new attribution beyond the cited sources.\n\n## Summary\n\n- Asserted construct slots: ${assertedConstructs.length}\n- Asserted constructs adjudicated unknown: ${unknown.length}\n- Asserted registered edges: ${assertedEdges.length}\n- Asserted registered edges adjudicated proxy-only or untested: ${unsupportedEdges.length}\n\n## Claim trail\n\n| Claim | Source type | Constructs asserted by source | Adjudicated unknown constructs |\n| --- | --- | --- | --- |\n${rows}\n\n## Limits\n\n- Decisions apply only to each recorded subject, unit, period, and evidence bundle.\n- This case frame was frozen before independent coding.\n- See the accompanying JSON for sources, locators, both independent row hashes, adjudication rationales, and institutional consequences.\n`;
  const mdPath=`${outputDir}/${item.case_id}.md`;writeFileSync(mdPath,md);outputs.push({case_id:item.case_id,json:jsonPath,report:mdPath,claims:auditClaims.length});
}
const outputManifest={status:'three_adjudicated_case_audits_built',decisions_sha256:manifest.decision_sha256,case_frame_sha256:createHash('sha256').update(readFileSync('ficcs/case_study_frame_v1.json')).digest('hex'),outputs};writeFileSync(`${outputDir}/MANIFEST.json`,JSON.stringify(outputManifest,null,2)+'\n');console.log(JSON.stringify(outputManifest,null,2));
